### ISSUE TITLE
Constant server crashes

### ISSUE THREAD

**Issue by yashairi** [tyon2006/MMO---Here-We-Go-#203] opened 2021-08-04 19:58 UTC
The server constantly disconnects me and restarts when I am exploring. May be a local issue at the grasslands where spawn is.

**Comment by tyon2006** [comment] 2021-08-06 23:36
This was caused by a bug in WAIG. Fixed in WAIG v1.3.1

https://www.curseforge.com/minecraft/mc-mods/where-am-i-going/files/3416692

**Closed by tyon2006** 2021-08-06 23:36 UTC
Labels: bug
